### ISSUE TITLE
Alternate status icons on mobile 

### ISSUE THREAD

**Issue by ElCid87** [ebullient/obsidian-theme-ebullientworks#24] opened 2023-01-30 13:04 UTC
In Live Preview mode for Mobile, the icons for alternate status on display check boxes.

![Screenshot_20230130-080336.png](https://user-images.githubusercontent.com/11091508/215485300-1e6126ec-b973-4d56-a231-c500ada16321.png)

**Comment by ElCid87** [comment] 2023-01-30 13:05
This is a minor issue for me. Just reporting it for your awareness since you have been taking time to fix this issue.

**Comment by ebullient** [comment] 2023-01-30 13:28
Thank you! The styles must have changed again. Will have a look.

**Comment by ElCid87** [comment] 2023-01-30 19:03
Pic of source view (13050)
Pic of live preview (135226)
Pic of installed theme (135320)
Pic of Tasks Custom Statuses (135503) I just tapped the "Ebullientworks
Theme: Add 8 supported Statuses" button.

I am on an Android device.

I disabled the Tasks plugin. Excited Obsidian and started Obsidian, the
live preview is the same as pic 135226. The reading view with Tasks enabled
or disabled is correct and looks like pic 140228

**Comment by ebullient** [comment] 2023-01-31 16:13
Now have had proper time.. and the images didn't come through .. can you attach via browser rather than through email?

**Comment by ElCid87** [comment] 2023-02-02 12:14
Erin,

Please accept my apologies for the delay. Yes, of course, will get you the
pics today.

BTW, I still love the work. It is far better than I could have done. So
many themes are plain business like or super dark/techie.

Yours feels more personal and closer to a physical journal.

Don't know if that was the intent, but it makes me feel more at ease using
Obsidian.

Steven

**Comment by ebullient** [comment] 2023-08-16 20:48
Closing as I can't reproduce this, and there have been no other reports. Please reopen if this is still happening.

**Closed by ebullient** 2023-08-16 20:48 UTC
